// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace NotaFiscal
{
    public partial class NotaFiscalContextModel
    {
        partial void Initialize()
        {
            var importacaoNotaXml = ImportacaoNotaXmlEntityType.Create(this);
            var produtoNotum = ProdutoNotumEntityType.Create(this);
            var totalNotum = TotalNotumEntityType.Create(this);

            ProdutoNotumEntityType.CreateForeignKey1(produtoNotum, importacaoNotaXml);
            TotalNotumEntityType.CreateForeignKey1(totalNotum, importacaoNotaXml);

            ImportacaoNotaXmlEntityType.CreateAnnotations(importacaoNotaXml);
            ProdutoNotumEntityType.CreateAnnotations(produtoNotum);
            TotalNotumEntityType.CreateAnnotations(totalNotum);

            AddAnnotation("ProductVersion", "6.0.7");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
