// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using nf_xml_api.Models;

#pragma warning disable 219, 612, 618
#nullable enable

namespace NotaFiscal
{
    [DbContext(typeof(NotaFiscalContext))]
    public partial class NotaFiscalContextModel : RuntimeModel
    {
        static NotaFiscalContextModel()
        {
            var model = new NotaFiscalContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static NotaFiscalContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
