version: '3.9'
services:
  app:
    container_name: nfe-api-prod
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5004:80"
    depends_on:
      - db
  db:
    container_name: nota-fiscal-prod
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "!n0ta_app"
      ACCEPT_EULA: "Y"
    ports:
      - 1404:1433