version: '3.9'
services:
  app:
    container_name: nfe-api-stage
    image: nfe-importacao-api
    # build:
    #   context: ./
    #   dockerfile: Dockerfile-STAGE
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "5003:80"
    networks:
      - back-end
    depends_on:
      - db
  db:
    container_name: nota-fiscal-stage
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "!n0ta_app"
      ACCEPT_EULA: "Y"
    ports:
      - 1403:1433
    networks:
      - back-end
      
networks:
  back-end: